on:
  # Trigger analysis when pushing in master or pull requests, and when creating
  # a pull request.
  push:
  pull_request:
    types: [opened, synchronize, reopened]
name: a11y tests
env:
  CI: true
  REDIS_SUPPRESS: true
  REQUIRED_OS_PACKAGES: "gconf-service, libasound2, libatk1.0-0, libc6, libcairo2, libcups2, libdbus-1-3, libexpat1, libfontconfig1, libgcc1, libgconf-2-4, libgdk-pixbuf2.0-0, libglib2.0-0, libgtk-3-0, libnspr4, libpango-1.0-0, libpangocairo-1.0-0, libstdc++6, libx11-6, libx11-xcb1, libxcb1, libxcomposite1, libxcursor1, libxdamage1, libxext6, libxfixes3, libxi6, libxrandr2, libxrender1, libxss1, libxtst6, fonts-liberation, libappindicator1, libnss3, lsb-release, xdg-utils"
jobs:
  build:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'
          # Defaults to the user or organization that owns the workflow file
          scope: '@octocat'
      - name: Run install
        uses: borales/actions-yarn@v4
        with:
          cmd: install # will run `yarn install` command
      - name: Run webpack

        with:
          cmd: webpack # will run `yarn webpack` command
      - name: install bits
        run: sudo apt-get update && sudo apt-get install -y libgbm-dev
      - name: Run test:a11y
        uses: borales/actions-yarn@v4
        with:
          cmd: test:a11y --runInBand --forceExit # will run `yarn test:a11y` command
