on:
  # Trigger analysis when pushing in master or pull requests, and when creating
  # a pull request.
  push:
  pull_request:
    types: [opened, synchronize, reopened]
name: a11y tests
env:
  CI: true
  REDIS_SUPPRESS: true
jobs:
  build:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          registry-url: 'https://registry.npmjs.org'
          # Defaults to the user or organization that owns the workflow file
          scope: '@octocat'
      - name: Run install
        uses: borales/actions-yarn@v4
        with:
          cmd: install # will run `yarn install` command
      - name: Run webpack
        uses: borales/actions-yarn@v4
        with:
          cmd: webpack # will run `yarn webpack` command
      - name: Run test:a11y
        uses: borales/actions-yarn@v4
        with:
          cmd: test:a11y  # will run `yarn test:a11y` command
