on:
  # Trigger analysis when pushing in master or pull requests, and when creating
  # a pull request.
  push:
  pull_request:
    types: [opened, synchronize, reopened]
name: a11y tests
env:
  CI: true
  NODE_OPTIONS: --max-old-space-size=4096
  REDIS_SUPPRESS: true
jobs:
  build:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'
          # Defaults to the user or organization that owns the workflow file
          scope: '@octocat'
      - name: Run install
        uses: borales/actions-yarn@v4
        with:
          cmd: install # will run `yarn install` command
      - name: Run build
        uses: borales/actions-yarn@v4
        with:
          cmd: build # will run `yarn build` command
      - name: Run test:routes
        uses: borales/actions-yarn@v4
        with:
          cmd: test:routes --forceExit # will run `yarn test:routes` command
